### ISSUE TITLE
无法扫描包含 utf-16 riff info 的 wav 文件

### ISSUE THREAD

**Issue by Ferry-200** [Ferry-200/coriander_player#10]
考虑支持 WAV？
~鬼知道我为什么有些音乐是 WAV 格式~

_Originally posted by @Wenti-D in https://github.com/Ferry-200/coriander_player/issues/6#issuecomment-2047384793_

**Comment by Wenti-D** [comment]
是找不到文件。多怪啊

**Comment by Ferry-200** [comment]
可以分享那个音乐文件出来吗？或者直接QQ就好。之前那个 comment 里面的记录可以找到。

**Comment by Ferry-200** [comment]
虽然现在 lofty 正在着手支持，但目前建议转成 utf-8 的编码。

**Comment by Wenti-D** [comment]
然而这样做的代价就是其他所有软件都无法读取，除非我启用 UTF-8 支持，但如此又会导致别的软件奇怪的编码问题，所以我选择不急。

**Comment by Ferry-200** [comment]
所以现在 wav 的读取竟然是只固定使用用户系统默认编码的，，。我还以为会有试错的可能。

**Comment by Ferry-200** [comment]
现在解决了！可喜可贺，可喜可贺。
现在的方案是：尝试在 Lofty 无法读取标签时通过 Windows 获取。唯一的问题是不清楚怎么通过 Windows 获取采样率。
![image](https://github.com/Ferry-200/coriander_player/assets/98510207/2313404f-aa78-4476-b3d0-3e4c924229b6)

**Comment by Wenti-D** [comment]
好！

比特率一般大家都用的 kbps 吧。
