### ISSUE TITLE
[改进] 1、网络共享文件夹访问，每次打开时需要加载很久；2、是否可以新增自动下载最优歌词文件至歌曲文件夹；3、是否可以新增自动下载歌曲的专辑及歌手图片，并完善到歌曲信息中

### ISSUE THREAD

**Issue by Zheny918** [Ferry-200/coriander_player#100]
### 附带PR？

否

### 功能描述

[改进] 1、网络共享文件夹访问，每次打开时需要加载很久；2、是否可以新增自动下载最优歌词文件至歌曲文件夹；3、是否可以新增自动下载歌曲的专辑及歌手图片，并完善到歌曲信息中

**Comment by Ferry-200** [comment]
1. 这应该是 Windows 的问题
2 和 3 因为版权问题不做
