### ISSUE TITLE
[BUG] 点击右上角关闭按钮无法关闭界面

### ISSUE THREAD

**Issue by activityz** [Ferry-200/coriander_player#105]
### 附带PR？

否

### 版本

v1

### 问题描述

点击右上角关闭按钮无法关闭界面

### 重现步骤

点击右上角关闭按钮无法关闭界面

### 预期行为

关闭应用或退出应用

**Comment by XingZhe-Li** [comment]
完全一样的BUG，版本v1.1.0。
任务管理器杀掉以后再开正常了。

附加信息：经过几次尝试，初次启动会关不掉，可以通过删除`%username%\AppData\Roaming`下的`com.example`文件夹复现（包名是不是取的随意了一点😂）。

非常好播放器，Windows平台小体积高颜值的音乐播放器不多，Coriander技术选型又新，非常期待👍。

**Comment by Ferry-200** [comment]
> 完全一样的BUG，版本v1.1.0。
> 任务管理器杀掉以后再开正常了。
> 
> 附加信息：经过几次尝试，初次启动会关不掉，可以通过删除`%username%\AppData\Roaming`下的`com.example`文件夹复现（包名是不是取的随意了一点😂）。
> 
> 非常好播放器，Windows平台小体积高颜值的音乐播放器不多，Coriander技术选型又新，非常期待👍。

那我知道是什么原因了。非常感谢。
