### ISSUE TITLE
[新功能] 建议在查找结果页面加一个查找条

### ISSUE THREAD

**Issue by FisherRong** [Ferry-200/coriander_player#106]
### 附带PR？

否

### 功能描述

现在在查找结果页面没有查找条。可以通过左上角的返回键返回有查找条的页面。但是这样似乎有点反直觉hhh，我第一次用的时候找了大半天都不知道怎么重新开始一次查找。
![image](https://github.com/user-attachments/assets/41573b1f-cd90-4223-919e-6fac2d5fc3a5)

### 新功能的分类（选填）

UI

**Comment by Ferry-200** [comment]
现在的搜索页确实过于简陋，我会好好重新设计的

**Comment by FisherRong** [comment]
您好，我已收到

**Comment by Ferry-200** [comment]
> 您好，我已收到

没必要这么正式😂
