### ISSUE TITLE
[改进] 页面UI以及软件图标

### ISSUE THREAD

**Issue by YogruTi** [Ferry-200/coriander_player#112]
### 附带PR？

否

### 功能描述

亲爱的开发者，

在众多开源音乐软件中，您的作品无疑是其中的佼佼者。然而，我注意到一个普遍现象：在追求新功能的创新过程中，一些开发者可能会忽视对软件核心操作逻辑和性能的持续优化。这种趋势往往会导致软件变得臃肿，性能下降，最终可能成为软件崩溃的隐患。

我对您的软件持有很高的期望。在新兴的音乐软件市场中，您的作品在性能、用户界面(UI)和操作逻辑方面都达到了及格线。我真诚地希望您能保持初心，继续致力于软件的优化工作。

请记住，持续的改进和对用户体验的深入关注是软件长期成功的关键。我期待看到您的软件在未来能够达到更高的标准，成为用户心中的首选。PS：注意到当前的图标设计似乎与软件的整体风格不太匹配。一个精心设计的图标不仅能够提升软件的视觉效果

### 被改进功能的分类（选填）

UI,UI布局，性能，以及软件图标

**Comment by Ferry-200** [comment]
ai 写的我不看（doge

**Comment by YogruTi** [comment]
我的错，太懒了，也就是ui布局和操作逻辑，性能目前加可以，刚才用着没办法直接关闭软件要在任务栏右键关闭，然后就是尺寸左右开源调上下不可以，最后就是主题设置希望可以更多选择，列如lx-music那样，最后就是软件图标太丑了，感谢
