### ISSUE TITLE
[BUG] 无法读取同文件夹下的lrc歌词

### ISSUE THREAD

**Issue by AnLazyOtter** [Ferry-200/coriander_player#113]
### 附带PR？

否

### 版本

1.1.0

### 问题描述

在同一文件夹下的lrc歌词会被程序自动读取，但是无法被加载到程序中
![sn4pjkze eyl](https://github.com/user-attachments/assets/40e33cac-64dd-49a2-8766-46c6f480a2ad)

### 重现步骤

1. 将歌词从本地OneDrive文件夹中“释放空间”
2. 播放歌曲Solar Storm.mp3
3. 可见到歌词文件Solar Storm.lrc会被自动下载（换言之，程序需求该文件，所以触发了OneDrive的自动下载功能）
4. 虽然设定了优先从本地获取歌词，但是程序还是跳过了本地的lrc，开始获取在线歌词。

我所使用的歌词文件：
[Solar Storm.zip](https://github.com/user-attachments/files/17045235/Solar.Storm.zip)

### 预期行为

应当首先加载本地歌词，而非尝试读取了下歌词，就放弃了。

### 其他信息

1. 是否我编制的歌词文件不符合格式要求才导致了问题？或者其他原因导致了不会加载本地歌词？
2. 顺带问一下在线歌词是从哪个网站查找的么？

**Comment by Ferry-200** [comment]
gb2312 编码的歌词不在支持范围内。换成 utf-8、utf-16 应该没问题。

**Comment by AnLazyOtter** [comment]
> gb2312 编码的歌词不在支持范围内。换成 utf-8、utf-16 应该没问题。


@Ferry-200 选择了UTF-8无签名，现在确实可以了。感谢答复。
另：也许可以考虑将这个加入到常见问题？
