### ISSUE TITLE
[新功能] 读取云文件时不需要完整下载文件

### ISSUE THREAD

**Issue by AnLazyOtter** [Ferry-200/coriander_player#114]
### 附带PR？

否

### 功能描述

如果要扫描的文件夹中的文件仅云端可用，则在扫描歌曲信息时，仅读取其属性，而无需完整下载文件。
现状：扫描歌曲时，需要将所有歌曲下载到本地才能完成扫描。
![ryy3fiod 114](https://github.com/user-attachments/assets/aacc8f09-d554-4871-b169-dc91e53820f8)

示例：在「简易歌曲播放器」中，可见歌曲已经添加到播放列表中了，但歌曲仍然处于“联机时可用”的状态。
（为啥不用简易歌曲播放器？因为作者停更了，而且播放部分歌曲的时候会有BUG，闪退）
![pqovl135 xvf](https://github.com/user-attachments/assets/f8655523-5682-4100-a327-82989e298dbc)

### 新功能的分类（选填）

歌曲扫描

**Comment by Ferry-200** [comment]
大概率不会做，因为这本来就是一个本地音乐播放器。做的话也只会支持alist
