### ISSUE TITLE
[改进] 排序处按钮不会随窗体拉伸，字体换行

### ISSUE THREAD

**Issue by s1805948721** [Ferry-200/coriander_player#117]
### 附带PR？

否

### 功能描述

排序处按钮随窗体拉伸，字体不换行
![image](https://github.com/user-attachments/assets/ced17f1a-9032-44f3-a9b6-273f8028148b)

### 被改进功能的分类（选填）

UI

**Comment by Ferry-200** [comment]
给个完整的截图好吗？我不清楚是宽度多少时才会出现这个问题

**Comment by Ferry-200** [comment]
那就不限制这个按钮的宽度了。

**Comment by s1805948721** [comment]
我这里是任意宽度

**Comment by s1805948721** [comment]
只要这个按钮还能显示出来

**Comment by s1805948721** [comment]
最短：
![image](https://github.com/user-attachments/assets/2b297aed-c94c-4267-bdf7-950edbbc1daf)
最长（1600)：
![image](https://github.com/user-attachments/assets/42f8f4d0-63fb-4b71-92f0-2594e4d5c765)

**Comment by Ferry-200** [comment]
修复了

**Comment by s1805948721** [comment]
> 修复了，下版本吧
😘🎉
假期快乐
