### ISSUE TITLE
[BUG] smb获取不到全部歌曲

### ISSUE THREAD

**Issue by Run-os** [Ferry-200/coriander_player#118]
### 附带PR？

否

### 版本

1.1.0

### 问题描述

 下图为添加的smb文件夹，可以看到只有8首歌曲
![image](https://github.com/user-attachments/assets/7150459c-2fc3-49ae-bea5-c06d8fc8f0de)
下图为文件管理器查看到的同一文件夹的界面，可见有180+歌曲
![image](https://github.com/user-attachments/assets/5d6b65d4-0363-4d86-9a86-eb4d0081e176)

### 重现步骤

添加smb文件夹为网络映射

### 预期行为

获取到全部歌曲

**Comment by Ferry-200** [comment]
目前没做这方面的适配。现在应该只支持纯本地的读取。
