### ISSUE TITLE
SMTC 支持

### ISSUE THREAD

**Issue by Seayay** [Ferry-200/coriander_player#12]
![image](https://github.com/Ferry-200/coriander_player/assets/92374733/9059a15b-764f-4ee2-959a-45c89c9c8768)

Chrome、Spotify 等软件播放时可以在 Windows 这里看到信息同时控制播放，希望能够提供支持

**Comment by Ferry-200** [comment]
已完成。详见：[comment](https://github.com/Ferry-200/coriander_player/issues/24#issuecomment-2082023243)
