### ISSUE TITLE
[改进] 使用 Musixmatch 作為歌詞來源

### ISSUE THREAD

**Issue by ElliotCHEN37** [Ferry-200/coriander_player#128]
### 附带PR？

否

### 功能描述

可以參考: MxLRC, LyricsPlus (Spicetify 的 custom app)。這兩個是我在 Windows 平台上面看到的可參考的項目

### 被改进功能的分类（选填）

歌詞

**Comment by ElliotCHEN37** [comment]
https://github.com/fashni/MxLRC

**Comment by Ferry-200** [comment]
大陆基本连不上 musixmatch，所以应该不会做
