### ISSUE TITLE
[新功能] 最小化到系统托盘

### ISSUE THREAD

**Issue by immortal521** [Ferry-200/coriander_player#134]
### 附带PR？

否

### 功能描述

能否像很多软件一样可以关闭窗口后最小化到系统托盘按钮中，而不是停留在任务栏中

**Comment by Ferry-200** [comment]
duplicate of #95, #72, #68

说实话我不太喜欢最小化到系统托盘这个功能。

另外说一下我对这个功能的看法：

我确实可以简单地直接最小化到系统托盘。但由于现在播放器播放内核和 UI 界面是**绑定在一起的**，所以最小化到系统托盘**不会减少任何内存占用**，怎么样都会有大概 250mb 的内存占用。

如果要实现这个功能，应该在把播放内核抽离出来之后再做。这样最小化到系统托盘之后，内存占用应该可以限制在 25mb 以内，非常低。这才是真正的最小化到系统托盘。

但说实话我目前还没能力做到这一点，所以先当做未计划然后关闭。
