### ISSUE TITLE
[BUG] 文件夹页面内，过长的文件夹路径会重叠

### ISSUE THREAD

**Issue by Wenti-D** [Ferry-200/coriander_player#138]
### 附带PR？

否

### 版本

1.5.0

### 问题描述

![image](https://github.com/user-attachments/assets/675cf882-baf8-4060-9bd3-8d0ac6642ca0)

### 重现步骤

弄一个巨长的文件路径就行。

### 预期行为

平常截断，鼠标移上去时滚动显示。

**Comment by Ferry-200** [comment]
忘记做截断了hhh

**Comment by Wenti-D** [comment]
其实列表和表格视图都会这样，只是列表宽很多而已（
