### ISSUE TITLE
自定义字体

### ISSUE THREAD

**Issue by Seayay** [Ferry-200/coriander_player#14]
![image](https://github.com/Ferry-200/coriander_player/assets/92374733/2af50ce6-abe7-4f77-9d23-9b1805f1eb7b)

自带的字体显示中文时效果并不是很好，希望可以自己选择显示字体

**Comment by Ferry-200** [comment]
会使用宋体作为默认字体。要选择字体的话只会支持 Windows/Fonts 下的字体。不会支持自行导入。

**Comment by Wenti-D** [comment]
其实这是 Windows 字体渲染的锅，如果用 MacType 之类的软件覆盖掉 Windows 字体渲染会好一些。

**Comment by Ferry-200** [comment]
其实也有 Flutter 默认使用西文字体的原因，换成中文字体是真的会很大改善这个问题。Flutter 在中文支持上是真的存在很多问题，比如如果不配置地区，还会出现中日韩文字混用的情况。
