### ISSUE TITLE
[改进] 自定义字体选择时显示字体本身而不是默认字体

### ISSUE THREAD

**Issue by 2315095914** [Ferry-200/coriander_player#148]
### 附带PR？

否

### 功能描述

自定义字体选择时显示字体本身而不是被默认字体覆盖全部

### 被改进功能的分类（选填）

设置-自定义字体-选择字体

**Comment by Ferry-200** [comment]
Flutter 不可以直接使用字体，而是需要先载入再使用。如果在字体选择页面使用对应的字体需要实时加载，内存占用会涨至 500MB 以上。目前先不做。
