### ISSUE TITLE
简单体验后的一些建议

### ISSUE THREAD

**Issue by windowBR** [Ferry-200/coriander_player#15]
### ① 歌曲排序方式应该有记录
**当前情况：** 当选择一种非默认的歌曲排序方式时，若切换到其他页面（如艺术家、专辑等），再切换回来排序方式会变回默认
**期望情况：** 选择一种其他排序方式后应该记录住该状态，在切换页面或退出软件重新启动都恢复原样
### ② 动效建议
在横屏播放详细页打开**歌词/播放列表**时可以加上封面向左移动、歌词/播放列表 向上推出（类似首页切换音乐、艺术家页面的切换效果）的效果，关闭 歌词/播放列表 反之；而二者切换时可直接套用首页页面切换效果或其他动效。
竖屏下则除了封面移动建议相同
### ③ Windows 通知
**当前情况：** 每播放完毕一首歌切换到下一首时会弹出 Windows 通知提示当前播放的歌曲
**期望情况：** 该通知不必要，可增加一个设置项开关
### ④ 任务栏显示
**当前情况：** 如图 
![image](https://github.com/Ferry-200/coriander_player/assets/46346833/525f7c5c-6c31-417b-9ef3-04b7da0c4580)
**期望情况：** 图标在未设计好时可暂用首页左上角音符图标等音乐相关现有图标代替，
任务名称可由当前的 **coriander_player** 更改为 **Coriander Player** 
### ⑤ 操作逻辑建议
1. 播放详细页可以考虑增加一个按住鼠标左键下拉退出详细页的操作，与当前退出动效相呼应
2. 对于系统返回键的行为：这里指的返回键是许多鼠标侧键会预设的那种系统级返回键，可以考虑将该按键的行为设置为 “处于播放详细页时按下返回键退出详细页；当处于其他页面时返回键作用等同于按下软件左上角的返回键”

**Comment by Ferry-200** [comment]
1. 在进度中
2. 动画是很多应用在早期阶段都会缺少的东西，至少在近期时间都不会考虑动画的问题
3. 在进度中
4. 在进度中
5. 1. 这不是移动端，没有必要实现那么复杂的动画。事实上你也不会在 Windows 应用上看到这种设计。
    2. 只会实现 ESC 快捷键和空格暂停/播放。其他的不做。

**Comment by windowBR** [comment]
理解，希望软件能越做越好，Windows 上一直都没找到什么很满意的本地播放器，这个播放器让我看到些心中所想的样子了🙏

**Comment by Ferry-200** [comment]
新版本更新啦，欢迎下载体验

**Comment by windowBR** [comment]
刚刚第一时间就下载了新版本进行了一段时间的体验，大部分地方比之前的版本确实更好用了，好评。之前的版本我主要还是用于尝鲜体验，现在的版本我会考虑用来当日常使用的播放器软件了
但于此同时也又发现一些新的可以提建议的地方

关于使用逻辑方面
1. 我发现了目前版本的歌曲扫描功能并不会扫描选定文件夹下的子文件夹内的音乐，我认为这里可以做一个选项，让用户选择是否扫描子文件夹
2. 搜索有一个单独的全局页面固然好，但我认为同时也在**音乐、艺术家、专辑**等界面上方添加一个对应界面的搜索框，来快速定位希望查找的条目，这样的操作逻辑会更符合直觉，而原先的搜索页面也仍然保留用作全局搜索
3. 您之前提到的会实现 ESC 与 空格键 的快捷键操作似乎在当前版本并未实现，希望能在之后的版本中实装

关于 UI 的个人建议方面（图一乐当个参考就好，毕竟 UI 设计大家都有自己的审美）
1. 在**歌词**界面中，最开始的几句当前逻辑为歌词整体不移动，高亮部分下移，然后高亮部分移动到固定位置后歌词整体移动而高亮部分位置相对固定。我认为可以在歌词上方添加留白以达到始终为歌词整体移动而高亮部分位置相对固定能让逻辑更加统一。然后是高亮部分的歌词可以字体放大以突出（不过我感觉这部分的过渡动画逻辑可能比较复杂，不好做的话就算了吧）
2. **全局搜索**页面中，当前搜索结果是纯文字。我认为可以像**音乐、艺术家、专辑**界面中那样同时显示对应的图片以便用户快速定位信息
3. 在**音乐、播放列表、主界面下方的播放控件**界面中，可以将**歌名**的字体采用放大/加粗等手段来与**艺术家、专辑名**做出区分，如同**播放详细页**的封面上方的信息那样

总的来讲感觉这次更新确实提升挺大了，也希望作者能继续将这个播放器打磨得更上一层楼👍

**Comment by Ferry-200** [comment]
转到 #56
