### ISSUE TITLE
[新功能] 提供关闭软件时歌曲播放记忆选项

### ISSUE THREAD

**Issue by 2315095914** [Ferry-200/coriander_player#150]
### 附带PR？

否

### 功能描述

提供一个选项能够在打开软件时接续上次关闭时正在播放的歌曲/Do nothing
or 仅保存播放列表
### 新功能的分类（选填）

播放

**Comment by Ferry-200** [comment]
duplicated of #55

**Comment by 2315095914** [comment]
👌
