### ISSUE TITLE
[BUG] flac格式无法显示但是可以播放

### ISSUE THREAD

**Issue by mowei223** [Ferry-200/coriander_player#159]
### 附带PR？

否

### 版本

1.10

### 问题描述

大佬你好， flac格式无法显示但是可以播放可以解决不？

### 重现步骤

![89f807603d1c8918eeab69386a2b5e31](https://github.com/user-attachments/assets/7176f619-c61d-40a4-a0bd-fef8009f5a8d)

### 预期行为

显示

**Comment by mowei223** [comment]
![Uploading QQ20241109-172505.png…]()

**Comment by mowei223** [comment]
1
![Uploading QQ20241109-172505.png…]()

**Comment by Ferry-200** [comment]
最新版本应该可以显示歌曲的文件名，试着用最新版看看

**Comment by mowei223** [comment]
> 最新版本应该可以显示歌曲的文件名，试着用最新版看看
请问Releases 里的1.5版本是最新的么？我试了也不行呢

**Comment by mowei223** [comment]
好了。我重新扫描后就正常了，真奇怪，谢谢~~
