### ISSUE TITLE
一些界面建议

### ISSUE THREAD

**Issue by Tesla-AC** [Ferry-200/coriander_player#16]
1. 播放界面下边的几个按钮可以添加鼠标放上去时提示文字嘛，虽然点几下可能就能猜到每个按钮作用，不过有提示感觉更舒服。
![1 播放界面](https://github.com/Ferry-200/coriander_player/assets/56549504/ca058571-db23-41d7-a147-153c508672bf)

3. 音乐列表右边的下拉按钮颜色在夜间模式下不明显，是不是忘记修改夜间模式的配色啦
4. 我文件夹内有5000+首，但是感觉列表往下拉没有加载那么多，可以在列表的左上角的音乐这里添加一个音乐总数嘛
5. 音乐列表界面右边有点空空的，不知道可不可以把每首音乐的时长显示在这里（真的很想要这个功能QAQ
![音乐列表](https://github.com/Ferry-200/coriander_player/assets/56549504/3ecb5b93-e089-4ce3-b02e-c4ce8a292a96)
![2 播放列表](https://github.com/Ferry-200/coriander_player/assets/56549504/c2954bfe-c335-424a-b5d7-b67456be502c)

**Comment by Ferry-200** [comment]
不错的建议，下个版本见😋

**Comment by Tesla-AC** [comment]
> 不错的建议，下个版本见😋

好耶😋

**Comment by Ferry-200** [comment]
@Tesla-AC 你可以下载最新版本看看是否有五千多首音乐吗？现在新版本包含你想要的在页面显示音乐数量的功能。我没有那么多首音乐，没办法做大数量的测试，希望你可以帮我。（如果放音乐的文件夹下包含子文件夹，请把子文件夹也加到文件夹目录去）

**Comment by Tesla-AC** [comment]
![214142a30957640da97ee573ff285e4c](https://github.com/Ferry-200/coriander_player/assets/56549504/e67da139-8940-4e9f-9351-d83cb0d6649a)

乐曲数量可以正常显示，音乐时长的秒数显示好像还有些问题，可以调整秒位始终以两位数显示嘛

**Comment by Ferry-200** [comment]
> 秒位始终以两位数显示

**Comment by Tesla-AC** [comment]
又发现一个深色模式的字体颜色问题，在创建歌单的输入框里字体不是亮色

![image](https://github.com/Ferry-200/coriander_player/assets/56549504/2108997d-3b76-4531-b13d-dac61050348c)

**Comment by Ferry-200** [comment]
感谢提醒。另外我建议，以后发现问题时，不要再已经关闭的议题上回复，可以新开一个议题。

**Comment by Tesla-AC** [comment]
>以后发现问题时，不要在已经关闭的议题上回复，可以新开一个议题。

感谢建议。看了你的项目后我最近一直在尝试学习 flutter，可是克隆到本地的代码一堆爆红的问题让我毫无解决思绪，请问有什么推荐的 flutter 教程吗，谢谢。另外想问下这个项目依赖固定版本的 flutter 吗，我安装的是 3.19.6 版本的。

**Comment by Ferry-200** [comment]
> 看了你的项目后我最近一直在尝试学习 flutter，可是克隆到本地的代码一堆爆红的问题让我毫无解决思绪，请问有什么推荐的 flutter 教程吗，谢谢。另外想问下这个项目依赖固定版本的 flutter 吗，我安装的是 3.19.6 版本的。

我建议先了解 Dart 语言：[Dart 概览](https://dart.cn/overview)
然后接着学习 Flutter：[Flutter 中文文档](https://flutter.cn/docs)
这个项目现在的 Flutter 版本也是 3.19.6。我尽量不去依赖固定版本，而是跟随官方更新。

代码一堆爆红应该是没有获取 Packages。你可以在 vs code 的终端里运行 `flutter pub get` 来获取。
如果还有其他问题，可以加 qq：2110197157 来交流。
