### ISSUE TITLE
[BUG] 无法获取 DSF 文件的元信息

### ISSUE THREAD

**Issue by sherlcok314159** [Ferry-200/coriander_player#161]
### 附带PR？

否

### 版本

1.5.0

### 问题描述

 用音乐标签修改后，依然无法识别到任何信息，标签编码格式是 UTF-16

### 重现步骤

找到任意的 DSF 格式文件即可

### 预期行为

信息被正常读取

**Comment by Ferry-200** [comment]
duplicated of #98
