### ISSUE TITLE
[改进] 是否考虑添加歌词锁定功能

### ISSUE THREAD

**Issue by linyeyuyue** [Ferry-200/coriander_player#167]
### 附带PR？

否

### 功能描述

rt

### 被改进功能的分类（选填）

歌词ui

**Comment by Ferry-200** [comment]
桌面歌词不是已经有锁定了吗？

**Comment by linyeyuyue** [comment]
> 桌面歌词不是已经有锁定了吗？

![image](https://github.com/user-attachments/assets/0e6b837a-3122-47cb-80a4-d19acc51000b)
诶？

**Comment by linyeyuyue** [comment]
嘶，为什么我会没有右边的锁定按钮，直接用的exe

**Comment by linyeyuyue** [comment]
> 嘶，为什么我会没有右边的锁定按钮，直接用的exe

用的之前的版本，我的（）
