### ISSUE TITLE
磁盤讀取問題 Disk Reading Problem

### ISSUE THREAD

**Issue by lijl070** [Ferry-200/coriander_player#17]
![image](https://github.com/Ferry-200/coriander_player/assets/61622695/22c449e0-e74b-46fd-bd19-1389e3dc2fbf)
when i add folder at USB hard drives, it looks like the picture above ↑, and the sound is intermittent. 
and this problem was gone when i was using a SSD or an HDD which connected with SATA to my computer directly.
i guess there is some problem in reading files from disks.
Maybe make it read the whole file to memory at first will avoid this problem.

**Comment by lijl070** [comment]
it's ok, but having a multilang version will be better. btw, Thank you for providing us this brilliant music player.

**Comment by lijl070** [comment]
Mine is a HDD (USB 3.0). I have tested these connections:
1.the HDD to a USB2.0 port.
2.a USB drive to the 2.0 port.
3.another HDD to the 2.0 port.
4.the USB drive to a 3.0 port.
5.the HDD (in connection 3) to the 3.0 port.
and both it worked properly.
But the problem was still there when i read files from that drive connected to that 3.0 port.
I have no idea about it, perhaps it was caused by windows explorer or something else.
At least there isn't any bugs in this program. ;)

**Comment by Ferry-200** [comment]
> Read the file asynchronously. 
> When enabled, the file is read and buffered in parallel with the decoding, to reduce the chances of the decoder being affected by I/O delays. 
> This can be particularly useful with slow storage media and/or low latency output.

Following the documentation, I tried enabling the BASS_ASYNCFILE tag during playback. Since I was unable to reproduce the bug, please download this test version and test if it has fixed the issue. Thanks!

[for test](https://drive.google.com/file/d/1pfXd0sA6ocbwZtofIclwlMd_EceJ7w23/view?usp=sharing)
