### ISSUE TITLE
[BUG] 崩溃、本地歌词

### ISSUE THREAD

**Issue by fhxcc123** [Ferry-200/coriander_player#170]
### 附带PR？

否

### 版本

1.5.0

### 问题描述

问题：偶发崩溃现象；有时会突然没声音，点击独占模式才恢复正常

问题：有时设置中设置了默认本地歌词，但还是会自动在线匹配（忘记歌曲是有还是无歌词了），希望默认本地歌词时都使用本地歌词（即使无歌词）

问题：软件导入歌曲的极限大约是多少首呢？

### 重现步骤

未知

### 预期行为

修复bug

**Comment by Ferry-200** [comment]
2. 注意一下设置里的描述是：首选歌词来源
3. 没测试过
