### ISSUE TITLE
[改进] 整理了一系列使用上的问题

### ISSUE THREAD

**Issue by Panda-Panta** [Ferry-200/coriander_player#172]
### 附带PR？

否

### 功能描述

整理了几个使用上的问题：
1.在歌单里右键歌曲没有直接“从歌单中删除”的选项，只能先多选，再移除出歌单
2.在一个选项页里面的时候，点左边菜单栏的同一个选项没法返回第一级界面
3.建议加一个长按左键进行多选
4.桌面歌词如果是双行歌词，下面一行显示不全，而且没法自定义歌词框长宽
5.建议加一个侧键返回的功能
6.能不能加上把在线歌词写入音乐的标签里的功能
7.歌单可不可以加个右键菜单“删除”“重命名”之类的，以及在空白处可以右键新建歌单
8.能不能加个刷新功能，编辑完标签后还得关了重开才能看到修改后的歌
9.左边菜单的“文件夹”可不可以再这一页里设置添加扫描哪些文件夹，可以加个“添加”按钮，也是最好有个右键添加
10.标题框位置的歌词，双行歌词中间会有个“|”分隔符，而不是显示双行
11.搜索功能建议直接放在音乐页面或者标题框位置

**Comment by Ferry-200** [comment]
1. 也许后面会加上
2. 预期行为
3. 你有在电脑上见过这种交互吗
4. 你可以在出现双行歌词时调整字体大小，会自动适应
5. 你可以使用 esc 键
6. 不能
7. 右边有修改按钮啊
8. 你可以去设置重新扫描
9. 也许？
10. 预期行为
11. 谢谢建议
