### ISSUE TITLE
[改进] 专辑浏览页展示的专辑封面可以改大吗，会更好看

### ISSUE THREAD

**Issue by FisherRong** [Ferry-200/coriander_player#174]
### 附带PR？

否

### 功能描述

专辑浏览页展示的专辑封面可以改大吗，会更好看，如下图：
![image](https://github.com/user-attachments/assets/6b66b590-3e5a-40bc-be5d-41cecfcad071)

现在的界面：
![image](https://github.com/user-attachments/assets/771c85dd-ccc4-4f79-b9a3-6b942fc6204b)

### 被改进功能的分类（选填）

UI

**Comment by FisherRong** [comment]
补充：其实现在的UI也挺好看的，虽然封面比较小，但是展示的信息更多，开发者可以权衡一下

**Comment by Ferry-200** [comment]
受内存占用限制，估计不会再增大图片大小。我不希望自己的播放器变成占用 500mb 的怪物

**Comment by FisherRong** [comment]
您好，我已收到
