### ISSUE TITLE
[改进] 建议固定用户选择的播放模式

### ISSUE THREAD

**Issue by shiqi156** [Ferry-200/coriander_player#175]
### 附带PR？

否

### 功能描述

例如我在听歌时，在音乐播放界面选择随机播放，下次再打开coriander player需重新点击播放方式按钮。建议用户在音乐播放界面选择某一音乐播放方式后，下一次用户再次打开后仍是该播放模式。

### 被改进功能的分类（选填）

音乐播放页面的播放方式按钮

**Comment by Ferry-200** [comment]
#55

> 随机的话由于现在在很多界面都提供了随机播放按钮；直接点击歌曲播放时又会把整个列表作为播放列表；这样来看，如果保存随机状态似乎会弄出一些让人误解的行为。

**Comment by shing-yu** [comment]
这种应该close as not planned来着（小声）
