### ISSUE TITLE
建议反馈

### ISSUE THREAD

**Issue by ohhh-yang** [Ferry-200/coriander_player#2]
1.在点击全屏时会有卡顿
2.全屏时封面与歌词很紧凑
3.这只是我的观感

**Comment by Ferry-200** [comment]
1. 实际上标题栏的所有控件在点击时都有一定延时。最小化、最大化和关闭的功能都是用社区的库实现的，后面我也许会自己实现一个，到时应该可以修复这个问题。
2. 我试着调一调，不一定改
