### ISSUE TITLE
ogg，M4A内嵌歌词适配

### ISSUE THREAD

**Issue by humosu** [Ferry-200/coriander_player#21]
不知道为什么，很多格式的内嵌歌词提取不出来，目前已知有ogg m4a，希望可以添加
还有，歌曲的内嵌封面可不可以不要强制拉伸
![屏幕截图 2024-04-20 225046](https://github.com/Ferry-200/coriander_player/assets/99652521/f9fbb964-c8cb-4604-9d04-76ffa3ef982f)
可以改成自动裁切，我觉得那样更好

**Comment by Ferry-200** [comment]
内嵌歌词目前只支持 flac 和 mp3。内嵌歌词的读取是因格式而异的，不能做到统一读取，后面会开始解决这个问题。
封面不拉伸可以

**Comment by Ferry-200** [comment]
现在支持以下音乐文件的内嵌歌词：
- aac
- aiff
- flac
- m4a
- mp3
- ogg
- opus
- wav（必须用 UTF-8 编码）

**Comment by Ferry-200** [comment]
新版本更新啦，欢迎下载体验
