### ISSUE TITLE
更改播放内核为 Windows 的 MediaPlayer 以自动支持 SMTC 功能

### ISSUE THREAD

**Issue by Ferry-200** [Ferry-200/coriander_player#24]
当前的播放内核是 BASS，能很好地完成播放各种格式的音乐的工作。它唯一的缺点是需要手动向 Windows 提供 SMTC 的支持，而 MediaPlayer 不需要。

现在有许多功能的实现需要依靠 Windows 的 API，比如在 Windows 更改主题时同步更改自身主题（现在需要重新启动应用）、SMTC 通知支持（#12）、已经实现的在文件资源管理器显示的功能等。

我希望改变使用 Windows API 的方式。现在是通过社区提供的 Dart 的 C++ 绑定调用。它不支持 Callback，难以继续使用。如果改为 Microsoft 提供的 windows-rs，再辅以 flutter rust bridge，可以用统一的方式实现监听主题变化、SMTC 通知、媒体播放等功能。这无疑增加了应用的可维护性。

**Comment by yhsj0919** [comment]
可以试试 https://pub.dev/packages/smtc_windows 基本能用，不过貌似不显示应用名称

**Comment by yhsj0919** [comment]
> 那我等着白嫖更好的了😄，我不会c,rust之类的语言

**Comment by Ferry-200** [comment]
> > 那我等着白嫖更好的了😄，我不会c,rust之类的语言

等我弄好了 Media Player 就尝试发到 pub 去😋

**Comment by Ferry-200** [comment]
> 那我等着白嫖更好的了😄，我不会c,rust之类的语言

老实说我也只会写 dart。写 c 是刷leetcode时喜欢造轮子然后才写，然后 rust 是接触到 flutter rust bridge 这个库才学的。

**Comment by Ferry-200** [comment]
已完成。播放内核仍是 BASS。感谢 windows-rs 和 flutter rust bridge。

https://github.com/Ferry-200/coriander_player/assets/98510207/f67abfe7-ceac-4d29-9fff-3804c43abd0b
