### ISSUE TITLE
排版错误：README 中缺少空格

### ISSUE THREAD

**Issue by gytxtx** [Ferry-200/coriander_player#25]
我发现这个存储库的 README 存在一些排版问题，对此我想提出一些建议：

将存储库的 **`README`**、"关于 (*GitHub 电脑版网页右侧的*)" 等文本排序方式 按照 https://github.com/sparanoid/chinese-copywriting-guidelines 的规则进行修改。

1. 添加空格
    根据 **sparanoid 的中文排版指南** 的规则，我们应该在相关链接和其他文本之间添加空格。
    相关链接: [sparanoid 的中文排版指南](https://github.com/sparanoid/chinese-copywriting-guidelines)

    ![image](https://github.com/Ferry-200/coriander_player/assets/62281844/1f7e33df-36e9-438e-b41c-ad7f5f3a78fb)

2. 善用 `Markdown` 排版
    Markdown 是一种强大的工具，可以帮助我们更好地排版文本。   

    例如，在文件名中使用 `Monospace`，这可以使文本看起来更美观。 

    就像这样: `index.html`
   ```md
   `index.html`
   ```

    ![image](https://github.com/Ferry-200/coriander_player/assets/62281844/2073e58a-f7a2-4e3f-856f-e03d0a4fb095)

3. 改用正确的大小写
    将 `Github` 改为 `GitHub`

---
如果我有不对的地方，请及时指正，感谢！

**Comment by Ferry-200** [comment]
感谢提醒。

我习惯把 Readme 当作便签来使用，没有太多考虑规范的问题。近期我会整理项目文档和 Readme，到时再进行相关优化。

**Comment by Ferry-200** [comment]
另外关于等宽字体的使用，我有不同意见：Markdown 的 `\`` 应该只用于展示代码，而不是碰着个英文单词就放代码块。

**Comment by gytxtx** [comment]
> 另外关于等宽字体的使用，我有不同意见：Markdown 的代码块应该只用于展示代码，而不是碰着个英文单词就放代码块。

🤔 你说得好像也有道理
