### ISSUE TITLE
按修改时间向下排序第22首歌播放音乐时卡住，歌曲文件大小必须够大，在其它播放器正常

### ISSUE THREAD

**Issue by s1805948721** [Ferry-200/coriander_player#29]
![image](https://github.com/Ferry-200/coriander_player/assets/141227996/1d257c5d-cfda-471b-92d6-72d7acea81c6)
第二次发生了，无法解决，不知原因，歌曲格式为flac，大小128M，
第一次Flac82M
更换把歌词来源无法解决

https://github.com/Ferry-200/coriander_player/assets/141227996/3ed69175-3b64-45d1-9d0e-29631b84c203

**Comment by s1805948721** [comment]
4453kbps

**Comment by s1805948721** [comment]
原来是另一首，更换那首歌后，过了一段时间换成了这首

**Comment by s1805948721** [comment]
第一个文件夹第22首歌，是这个问题，我移动这首歌换位置后还是这个位置的歌曲卡住

**Comment by s1805948721** [comment]
192kHz,4451kbps

**Comment by Ferry-200** [comment]
我觉得是在播放这两首音乐时发生了问题，跟排序啥的无关。也许你把它放到别的位置，就算不在你那什么第 22 个也会卡住。至于详细的我明天再看。

**Comment by Ferry-200** [comment]
@s1805948721 方便分享这两个音乐文件给我做测试吗？我没有规格那么高的音乐文件。

**Comment by s1805948721** [comment]
> @s1805948721方便分享这两个音乐文件给我做测试吗？我没有规格那么高的音乐文件。



> 我觉得是在播放这首比特率高的音乐时发生了问题，跟排序啥的相关性。也许你把它放到其他位置，就算不在你那什么第22个基因卡住。至于详细的我明天再看。

问题就是我更换位置后能播放了

**Comment by s1805948721** [comment]
> @s1805948721方便分享这两个音乐文件给我做测试吗？我没有规格那么高的音乐文件。

好的https://www.mediafire.com/file/3giwpqbuvi5tkm0/%25E5%25BC%25A0%25E5%258F%25B6%25E8%2595%25BE_-_%25E8%25BF%2598%25E6%2598%25AF%25E5%2588%2586%25E5%25BC%2580%25EF%25BC%2588Acoustic_Version%25EF%25BC%2589.flac/file

**Comment by Ferry-200** [comment]
> 问题就是我更换位置后能播放了

emmm... 奇怪

**Comment by s1805948721** [comment]
https://www.mediafire.com/file/4a4l1t2a347wfn6/%25E4%25B8%2581%25E4%25B8%2596%25E5%2585%2589_-_%25E7%2598%25A6%25E5%25AD%2590.flac/file
这是另一首 4215kbps

**Comment by s1805948721** [comment]
> > 问题就是我更换位置后能播放了
> 
> emmm... 奇怪

现在好像也不行了。。
![image](https://github.com/Ferry-200/coriander_player/assets/141227996/fec1af9a-309a-40e7-92e7-8ba05e99e143)
但是这种更高的也没事

**Comment by s1805948721** [comment]
<img width="760" alt="image" src="https://github.com/Ferry-200/coriander_player/assets/141227996/70db983c-3773-4332-9b85-c9a2f3ab24a5">

**Comment by s1805948721** [comment]
<img width="760" alt="屏幕截图 2024-05-02 193510" src="https://github.com/Ferry-200/coriander_player/assets/141227996/da94d9ff-42ec-46a4-ab75-a2ce09108eac">
现在好像移动位置也不行了。。
但是这种更高的也没事

**Comment by Ferry-200** [comment]
奇怪的是：我无法播放这两首音乐。如果我禁用 flac 插件，就可以正常播放。而且这些都跟位置无关。我觉得这是 bassflac 的问题，等我得到官方回复才能继续。

**Comment by s1805948721** [comment]
> 奇怪的是：是我无法播放这两首音乐。如果我禁用 flac 插件，就可以正常播放。而且这些都跟位置无关。我觉得这是 bassflac 的问题，等我得到官方回复才能继续。

好的
