### ISSUE TITLE
歌词来源优先级问题

### ISSUE THREAD

**Issue by ohhh-yang** [Ferry-200/coriander_player#3]
软件会优先匹配网络歌词，然而可能因为歌曲版本不同、没有更多的内嵌标识等等原因导致歌词不匹配问题，比如歌词一样但是时间对不上、歌词完全不同对不上等。
然而音乐文件的内嵌歌词一般来说都是正确的（个人的浅薄见解：要么音乐文件来自官方，已经校准了内嵌的各种信息；要么用户使用其他渠道自己嵌入了歌曲信息；或者其他情况）。
综上，我建议能提升本地嵌入歌词至最高优先级，没有内嵌歌词的话再来网络获取。

**Comment by Ferry-200** [comment]
也许添加个界面来选择默认的网络歌词然后保存这个选择才是更好的选择。

**Comment by ohhh-yang** [comment]
> 也许添加个界面来选择默认的网络歌词然后保存这个选择才是更好的选择。

嗯，对，设置界面加个选项✌️✌️✌️

**Comment by Ferry-200** [comment]
暂时降低了在线歌词的优先级。

https://github.com/Ferry-200/coriander_player/releases/tag/v0.0.5

之后会添加一个界面在本地歌词和几个匹配程度高的在线歌词中选择一个作为默认歌词，跟歌曲绑定。
至于怎么绑定还在考虑。也许是歌曲文件名和音乐平台上的id绑定。毕竟不可能直接存储歌词文本。

**Comment by Ferry-200** [comment]
v0.0.6添加了指定默认歌词的功能

https://github.com/Ferry-200/coriander_player/releases/tag/v0.0.6

这样应该可以解决这个问题
