### ISSUE TITLE
歌曲文件转移后无法扫描出音乐（刷新按钮不合理）

### ISSUE THREAD

**Issue by xiaoyu606** [Ferry-200/coriander_player#32]
具体情况是：我的电脑前段时间额外加了一块硬盘，将原来存于D盘的所有媒体文件（包括音乐）一股脑全转移到E盘了，在软件里也更改了路径，结果重启软件后一首音乐都扫描不出来

**Comment by xiaoyu606** [comment]
我又重新下载并重新添加路径后又恢复正常了，希望我这只是个例

**Comment by xiaoyu606** [comment]
这是我第一次提交issue，有些疏漏请谅解

**Comment by Ferry-200** [comment]
会不会是你在设置页面更改路径时没有点击添加按钮旁边的刷新按钮🧐

**Comment by xiaoyu606** [comment]
我天，还真是🤣

**Comment by Ferry-200** [comment]
那问题就是：那个刷新按钮太没有存在感了。

其实之前也有建议说这方面逻辑有问题（[在修改文件夹时自动保存](https://github.com/Ferry-200/coriander_player/issues/6#issuecomment-2049883189)）。
当时我的想法是修改后改变按钮样式以提醒用户点击；或是直接把这个界面做成弹窗，退出时保存。只不过我一直忘记这件事hhhh。

这次肯定会改，毕竟你在这里遇到问题了。

**Comment by Ferry-200** [comment]
新版本更新啦，欢迎下载体验
