### ISSUE TITLE
可视化、图标（各类ui及功能方面的改进建议）

### ISSUE THREAD

**Issue by Silicon7921** [Ferry-200/coriander_player#36]
![屏幕截图 2024-05-19 170837](https://github.com/Ferry-200/coriander_player/assets/107339377/997c133a-762c-4555-9bb6-79fa9ce76967)

1.播放器没有音量控制好怪异啊，希望能加一个音量控制，类似进度条的可拖动长条

2.拖动进度条时希望能在鼠标的光标上方显示定位的精确位置，不然不知道拖到几分几秒，没法精确定位时间

3.播放页面的背景好空虚...能不能加一个半透明的可视化？可以借鉴一下 https://github.com/lyswhut/lx-music-desktop

4.右键的歌曲信息既然时间戳都那么精确了 索性像mediainfo那样把编码，采样频率，比特率什么统统解析出来放上去罢

5.这个图标好拟物，一点都不material啊！相当突兀，完全不搭不是吗w(ﾟДﾟ)w

6.主题色希望可以填入HEX颜色，就加一个小小的输入框，不用色板

**Comment by Ferry-200** [comment]
1. Windows 本身就有音量合成器哦
2. 听起来不错
3. 这确实是一个很方便的实现音乐可视化的方案，我会试试
4. 我得研究怎么获取
5. 确实不 Material，后面我再换吧，毕竟这是 AI 做的
6. 在进度中，下一版本就可见。不过我还是会做一个色板出来。

**Comment by Silicon7921** [comment]
作者大大，个人认为windows的合成器实在不太好调出来（特别是win8~win10），而且点一下就没了（悲）
虽然eartrumpet这类软件可以代替，但是仍然需要安装一个额外软件（并且msstore相当煞笔）
并且目前页面上控件看着也比较空虚，出于对各类群体使用的便捷性考虑，希望作者大大可以再次考虑一下！

**Comment by Silicon7921** [comment]
图标这块有空说不定我可以画一个矢量图（）如果我看着也满意的话会提交一个pr

**Comment by Ferry-200** [comment]
那我试着弄弄看吧。另外期待你的图标！要提 pr 的话改 app_icon.ico 就好。

**Comment by Silicon7921** [comment]
明白！不过图标这块只能说“非曰能之，愿学焉”了。个人技术并不高超，学业繁忙请您不要抱太多期望

**Comment by Ferry-200** [comment]
没事没事，我也要复习期末考 hhh。你看我提交都已经断了两个周了。这些功能我应该是要到 6 月份才着手做的。

**Comment by chrjojame** [comment]
> 图标这块有空说不定我可以画一个矢量图（）如果我看着也满意的话会提交一个pr

现在的图标不好看，换个好看一点的，期待

**Comment by chrjojame** [comment]
> ~1. Windows 本身就有音量合成器哦~ ~2. 听起来不错~ ~3. 这确实是一个很方便的实现音乐可视化的方案，我会试试~ ~4. 我得研究怎么获取~ ~5. 确实不 Material，后面我再换吧，毕竟这是 AI 做的~ ~6. 在进度中，下一版本就可见。不过我还是会做一个色板出来。~
> 
> 目前进度：
> 
> * [x]  解码时的音量控制（替代音量合成器的音量控制）
> * [x]  拖动进度条时提示位置
> * [ ]  可视化
> * [x]  更详细的歌曲信息
> * [ ]  图标
> * [x]  更好的主题选择

好像不能随机播放

**Comment by EzekielChen2023** [comment]
期待图标能换个清晰贴近win11风格，其他方面目前觉得很完美，谢谢作者辛苦付出

**Comment by chrjojame** [comment]
> 正式版更新啦，欢迎下载体验

软件的图标还是和之前一样哎，有点丑

**Comment by Silicon7921** [comment]
画了几版图标都不怎么满意（悲

**Comment by Ferry-200** [comment]
> 画了几版图标都不怎么满意（悲

也许可以先发出来让我们看看hhh

**Comment by Silicon7921** [comment]
图标一定要96*96吗（）原来那个四周还有一圈透明像素，我的没有，这样没问题嘛

**Comment by Ferry-200** [comment]
只要是正方形的应该没问题

**Comment by Silicon7921** [comment]
pr提交力（喜）麻烦看看

**Comment by Ferry-200** [comment]
新图标 by @Silicon7921 
原本是 ico，为了放到 GitHub 的评论里，转成了 png 格式。
有什么意见可以在这里回复

![app_icon](https://github.com/user-attachments/assets/0ae7b055-91ed-4b2c-b7e2-66f5fee6ac7c)
