### ISSUE TITLE
[BUG]关于歌词切换的问题，以及其他缺陷

### ISSUE THREAD

**Issue by Silicon7921** [Ferry-200/coriander_player#37]
1.
![屏幕截图 2024-05-19 212236](https://github.com/Ferry-200/coriander_player/assets/107339377/8a7856c4-9750-4769-a202-4309a7fb15d9)

一首歌曲具备内置歌词，但是它“有点问题”，加载网络歌词非常慢
当我点击播放界面右下角的切换按钮后，会显示“无歌词“，按钮文字变为“无”
此时无论怎样疯狂点击按钮都不能切换，会卡在这个界面直到加载成功
但是如果没法加载呢？结果就是按钮失效，想用回内嵌也不行了，只能关掉重新加载歌曲(T_T)望修复！

2.
![屏幕截图 2024-05-19 213454](https://github.com/Ferry-200/coriander_player/assets/107339377/6c63de5c-e28d-4e5c-aaf1-fa0a8aa1d65e)

我发现间奏的三个点呼吸灯效果结束之后没有歌词滚动动画，是直接跳到下一行，十分甚至九分生硬
算是个动画bug
对了三个点建议去掉渐变和呼吸，直接变成瞬间亮起，类似卡拉ok，更适合预判下一句的开始时间，否则不仅没啥用还花哨

3.单曲循环那几个按钮状态在软件关闭之后不会保存，会回到默认状态，希望可以保存

4.播放的经过时长秒数在个位数的时候是单个的0:9,不是更规范的0:09（恼）希望统一格式

**Comment by Ferry-200** [comment]
了解
