### ISSUE TITLE
反馈两个小bug

### ISSUE THREAD

**Issue by wangzy21** [Ferry-200/coriander_player#38]
1. 深色模式下右键歌曲添加到歌单，歌单名称为黑色，看不清  
![屏幕截图 2024-05-20 184953](https://github.com/Ferry-200/coriander_player/assets/95275600/d6924b29-83c0-4dd5-bbf2-ba78fedf9a4d)

2. 歌单功能中删除歌曲和歌曲时间重合了
![屏幕截图 2024-05-20 185035](https://github.com/Ferry-200/coriander_player/assets/95275600/c3c63d97-89ae-4d42-bd71-71aa592192d5)

**Comment by Ferry-200** [comment]
下版本解决

**Comment by Ferry-200** [comment]
新版本更新啦，欢迎下载体验
