### ISSUE TITLE
打包可以试试 flutter_distributor

### ISSUE THREAD

**Issue by yhsj0919** [Ferry-200/coriander_player#4]
window_manager作者的作品，很强大

https://distributor.leanflutter.dev/

**Comment by Ferry-200** [comment]
看起来是整合了很多库，里面的msix支持也是直接调用的msix package。我会试试看。
主要Advanced Installer有一个主题很像Win11的APK Installer，然后我就试着用了一下

**Comment by Ferry-200** [comment]
这个是用的 inno setup，打包出来直接被 Windows defender 杀死hhh。看来我以后要记得提供带安装器的和直接 zip 打包的两种版本。这个 issue 标记为完成吧
