### ISSUE TITLE
发布版的小建议

### ISSUE THREAD

**Issue by Wenti-D** [Ferry-200/coriander_player#41]
发布 Release 时将打包好的 ZIP 命名为 `coriander_player_<version>.zip`。~~（我这下载软件的自动重命名已经命名到 `Release_5.zip` 了）~~

**Comment by Ferry-200** [comment]
了解

**Comment by Wenti-D** [comment]
哦我的老天你是住在 GitHub 吗（

**Comment by Ferry-200** [comment]
刚好在写代码。另外还有邮件通知
