### ISSUE TITLE
UI、功能优化小建议

### ISSUE THREAD

**Issue by Miles4364** [Ferry-200/coriander_player#46]
1. 歌曲播放的时间显示格式统一

   例如歌曲时间显示秒数不大于10的显示都是单位数。4:1 - 4:12

   期望统一显示格式为双数显示：4:01 - 4:12
  ![image](https://github.com/Ferry-200/coriander_player/assets/59217317/cd94c96a-4fd8-47ab-a78f-e92700c52310)

2. 播放界面按钮悬停可显示按钮名称

   例如播放页面的循环播放、随机播放、列表循环，鼠标悬停上显示按钮名称；

   单纯靠图标有可能会造成歧义，例如随机播放到底开启没有？

  
![image-20240611175233791](https://github.com/Ferry-200/coriander_player/assets/59217317/337be748-b342-437b-84ac-fdf22634552e)

3. 歌曲列表展示信息是否支持自定义？

   显示更多歌曲信息，例如音轨号，在以专辑为查看视角的时候可以快速定位专辑内歌曲

   参见win系统文件夹：
![image-20240611180212658](https://github.com/Ferry-200/coriander_player/assets/59217317/53bfc522-311a-469c-b533-345ca30eabf0)

4. 功能优化建议，是否做歌曲详细信息显示？

![image-20240611175449667](https://github.com/Ferry-200/coriander_player/assets/59217317/4edafba5-9209-48f9-ad86-0809c8bc0d32)

**Comment by Ferry-200** [comment]
1. 已经完成
2. 优化正在播放布局之后再做
3. 应该不会允许自定义。不过音轨号可以，下版本可见
4. 音乐页面右键歌曲可以发现歌曲信息的入口。这里是我忘记加上了

**Comment by Ferry-200** [comment]
已完成

**Comment by Ferry-200** [comment]
新版本更新啦，欢迎下载体验
