### ISSUE TITLE
歌词的问题

### ISSUE THREAD

**Issue by lbyisme** [Ferry-200/coriander_player#51]
请问是否可以实现歌词界面的逐字歌词的显示，就是类似QQ音乐那样一个字一个字的

**Comment by Ferry-200** [comment]
逐字歌词只支持 qrc 和 krc，这些都是从网上匹配的。如果匹配不到，你可以点击正在播放界面的更多按钮（三个点的那个），然后选择指定默认歌词。在那里选择 qq 或者 kugou 的歌词。

lrc 文件必须跟歌曲文件在相同的目录。现在加载本地歌词是优先内嵌歌词，然后才是 lrc 歌词。
