### ISSUE TITLE
光标离开歌曲的操作列表后仍变暗

### ISSUE THREAD

**Issue by createduser** [Ferry-200/coriander_player#53]
**Bug 概要**
选中歌曲后出现的操作列表，一旦光标经过操作列表，操作列表的其中一个操作就会像是光标在上面一样变暗，变暗的操作是哪一个取决于光标最后经过的是哪一个操作。此时单击（鼠标左、右、中）都会导致被选中的歌曲一直保持被选中的样式，但实际上并没有被选中

**复现步骤**
1. 从任意地方（尝试过文件夹、音乐、艺术家、歌单、专辑）进入音乐列表选中歌曲
2. 右单击任意歌曲
3. 光标经过操作列表的任意一个操作
4. 鼠标任意键单击

**预期行为**
歌曲一直保持被选中的样式

**截图**
![Coriander-Player-2024-07-31-16-34-24](https://github.com/user-attachments/assets/9e056702-59ce-47c3-bec3-97c08ce3e059)

**Comment by Ferry-200** [comment]
现在已修复，新版本发布后可见

**Comment by Ferry-200** [comment]
新版本更新啦，欢迎下载体验
