### ISSUE TITLE
ncm格式支持

### ISSUE THREAD

**Issue by chanmaoganda** [Ferry-200/coriander_player#58]
可否增加ncm的支持?
我最近写了一个ncm转换成mp3的rust库,效率不错
https://github.com/chanmaoganda/music_dumper
核心在这https://github.com/chanmaoganda/NcmDumpLib

**Comment by Ferry-200** [comment]
刚刚看了你的一些仓库，比如这个 dumper 和 audio player rs，我说一下自己的理解。

你这个 dumper 可以把 ncm 转换后以 vec u8 的形式给播放内核使用，也许转换后的整个布局是和 mp3 相同的？

audio player rs 里面用 rodio 播放这个 vec u8。

我这个播放器是使用 BASS 作为播放内核，它也允许我把 vec u8 传给它来播放音乐（不过我现在是直接通过文件路径创建流）。

所以可行的接入方案应该是在创建播放流时，通过文件后缀名判断是否是 ncm，如果是的话先用你这个解码成可用的音频数据，然后再播放。

整体来说应该简单，也不会引入太多侵入性的代码，可以一试。

如果上面有什么理解错的还请告诉我。

**Comment by Ferry-200** [comment]
dart 可没有那么好的播放内核。既然可行的话我待会试试

**Comment by chanmaoganda** [comment]
用rust做gui太折磨了, 又要考虑渲染的循环, 有要考虑播放器那边的循环, 这个所有权搞得我头疼

**Comment by Ferry-200** [comment]
> 用rust做gui太折磨了, 又要考虑渲染的循环, 有要考虑播放器那边的循环, 这个所有权搞得我头疼

我就学不来。你可以看仓库 rust 目录下的代码，我写的几乎不是 rust 该有的样子，完全不用指定生命周期之类的东西，全是 copy。

**Comment by chanmaoganda** [comment]
其实感觉可以用借用, 直接传as_ref()

**Comment by chanmaoganda** [comment]
只要你不返回借用,就不是很需要考虑生命周期

**Comment by Ferry-200** [comment]
问题来了：我该如何在不给 wyy 充钱的情况下获得 ncm 文件拿来测试

**Comment by Ferry-200** [comment]
可以把 Mp3Metadata 和 FlacMetadata 的 tag pub 出来吗？如果要支持 ncm，我希望可以像别的格式一样，在建立索引时就获取到它的标签。

**Comment by chanmaoganda** [comment]
可以了, 已经把tag公开了

**Comment by shing-yu** [comment]
感觉可能有版权问题（？

**Comment by Ferry-200** [comment]
> 感觉可能有版权问题（？

好像有又好像没有🧐弄了不宣传或许可以（

**Comment by shing-yu** [comment]
之前[unlock-music](https://github.com/unlock-music/unlock-music)就被DMCA Takedown了（）

**Comment by chanmaoganda** [comment]
确实, 我们应该只能提供解析功能, 别的应该都不能做

**Comment by Ferry-200** [comment]
那先放着，我是希望这个项目能活到两年以后我找工作的时候😂
