### ISSUE TITLE
征求新功能

### ISSUE THREAD

**Issue by Ferry-200** [Ferry-200/coriander_player#6]
现在项目处于发展的平缓期：我想把精力投入到这，但我不知道还应该添加什么功能。所以我希望可以收到一些新功能方面的需求（对已有功能的改进等）。

为方便跟踪需求，不再使用该议题收集新需求，请自行开新的 issue。

**Comment by Wenti-D** [comment]
考虑添加文件夹时搜索子目录。

**Comment by Wenti-D** [comment]
疑问：现在是以「同一时刻两行歌词」来标记歌词翻译的吗？
以及可不可以有自定义标记翻译的格式？

**Comment by Ferry-200** [comment]
> 现在是以「同一时刻两行歌词」来标记歌词翻译的吗？

相同时间戳的多行会被合并成一行，第二行起显示为小字体

lrc文件有别的支持标记翻译的格式吗？
或者你说的是逐字歌词？

如果是逐字歌词的话，好像qrc(qq)和krc(kugou)都不会直接在歌词里放翻译，而是通过别的接口获取。至于怎么获取我还没找到方法，我是web苦手🥲。伪造请求头啥的是真的看不懂啊🥲

**Comment by Wenti-D** [comment]
LRC 应该没有支持所谓多语言的格式，我个人的习惯是写在一行，以 `  //  ` 分割，但感觉不完美……
说实话逐字歌词的格式长什么样我还是从你的 README 里面知道的。

**Comment by Ferry-200** [comment]
> 写在一行，以  //  分割
有些歌词会包含斜线的。如果写死在程序里就会误伤其他歌词。甚至现在分割艺术家就有问题，包含顿号的比如“25時、ナイトコードで。”就会被当成两个艺术家。

按照 id3 的规范，应该只能拿`/`来分割。但是有很多软件在写标签时会用`、`，所以只好都切。虽然现在有提供自定义分割方法的操作，不过我没开放。

总的来说没有规范就是麻烦死的事情

**Comment by Wenti-D** [comment]
> 有些歌词会包含斜线的。如果写死在程序里就会误伤其他歌词。

的确，这正是我想的不完美之处。

> 总的来说没有规范就是麻烦死的事情

是这样的，真是太难了。😂

---

换个问题吧：考虑支持 WAV？

**Comment by LauShyO** [comment]
桌面歌词和任务栏歌词

**Comment by Ferry-200** [comment]
> 1.桌面歌词和任务栏歌词；
> 2.软件内支持调节音量；
> 3.支持点击关闭最小化到系统托盘；
> 4.切歌时的系统通知能够自行选择关闭，因为切歌快的时候通知老是会慢一拍，不如直接关闭，虽然可以在系统设置里关闭，但是感觉如果软件内提供一个开关感觉会更好；
> 5.主题模式支持跟随系统自动切换；
> 6.调整排序方式后切换到其它页面，重新返回后会恢复成默认；
> 7.歌词动效要是能像apple music那样感觉会更好看。

1、4、5、6在进度中

2. 音量合成器可以做到，我这就不实现了。效果上没差别的
3. 你可以点击最小化
7. 可以获取的歌词不支持我模仿 apple music 的动效。比如着重歌词有辉光特效需要歌词告诉我哪里该着重显示。另外，也有我能力不足的原因。

**Comment by Wenti-D** [comment]
又想了几个：
- 歌词支持偏移调整；
- 支持读取 LRC 中的 `[offset:xxx]`（偏移量）标签；
- 目前在设置中添加文件夹时不会自动刷新，建议添加时刷新一遍。

**Comment by Ferry-200** [comment]
> 歌词支持偏移调整；支持读取 LRC 中的 [offset:xxx]（偏移量）标签；

是我忘记了。主要我没遇到过需要考虑偏移值的情况

> 目前在设置中添加文件夹时不会自动刷新，建议添加时刷新一遍。

只要点击那个刷新按钮之后就会重新获取数据的。就是你需要重新进入音乐/专辑/艺术家/文件夹等页面，不要使用返回键。当时是为了保证这些页面的排序操作不影响到数据库才在每个页面使用独立的List。也就是说，现在这些页面现在都像静态页面一样。我试着添加通知这些页面重新获取数据的方法吧。

**Comment by Wenti-D** [comment]
> 只要点击那个刷新按钮之后就会重新获取数据的。

没错，我知道。只是觉得刷新按钮更应该为「用户主动刷新」而准备，可能是理念不一吧。

**Comment by Ferry-200** [comment]
也许只需要通过一些 UI 上的通知提醒用户点击刷新按钮是必要的。比如让它带上主题色，甚至是直接在那个位置弹一个Tip。

或者是直接把这个页面弄成弹窗，然后提供取消和更新的按钮。

**Comment by Wenti-D** [comment]
> 也许只需要通过一些 UI 上的通知提醒用户点击刷新按钮是必要的。比如让它带上强调色，甚至是直接在那个位置弹一个Tip。

我觉得也许可以。

> 或者是直接把这个页面弄成弹窗，然后提供取消和更新的按钮。

这个是 AIMP 类似的做法。

**Comment by s1805948721** [comment]
从文件夹页面进入无法对歌曲进行排序，在文件夹页面添加歌曲排序功能，还有文件夹页面的歌曲无法调整视图，只有单行视图，
添加文件夹时只能单选，不能多选

**Comment by OppaiSuki** [comment]
希望可以增加以下功能和特性：
1.既然是本地播放器，希望可以提供一个真正的全屏模式，或者说最大化时可以隐藏任务栏？windows的任务栏和目前软件的UI实在是太割裂了，不过这也是PC应用普遍存在的问题。
2.似乎是不支持触摸板的手势操作，暂停和切歌都没反应,用Powertoys指定程序和快捷键也不行，或许是我的操作问题？
3.跟随系统深色/浅色模式，这个晚上玉玉的时候打开播放器容易被亮瞎狗眼。
4.更多歌词页面样式，这个感觉优先度不是很高，我觉得默认的挺好看的
5.音乐可视化，我在曾经的老手机HTC和PSP上很喜欢开可视化

**Comment by Ferry-200** [comment]
> 1.既然是本地播放器，希望可以提供一个真正的全屏模式，或者说最大化时可以隐藏任务栏？windows的任务栏和目前软件的UI实在是太割裂了，不过这也是PC应用普遍存在的问题。
> 2.似乎是不支持触摸板的手势操作，暂停和切歌都没反应,用Powertoys指定程序和快捷键也不行，或许是我的操作问题？
> 3.跟随系统深色/浅色模式，这个晚上玉玉的时候打开播放器容易被亮瞎狗眼。
> 4.更多歌词页面样式，这个感觉优先度不是很高，我觉得默认的挺好看的
> 5.音乐可视化，我在曾经的老手机HTC和PSP上很喜欢开可视化

1. 在研究
2、3. 在进度中
4、5. 还得考虑一下

**Comment by OppaiSuki** [comment]
是的，4，5我其实觉得不实装问题也不大，但是1、2、3是作为现代播放器相对比较需要的功能。期待下一次更新




1105452612
***@***.***







                       
原始邮件
                       
                     

发件人："Ferry"< ***@***.*** &gt;;

发件时间：2024/4/23 17:07

收件人："Ferry-200/coriander_player"< ***@***.*** &gt;;

抄送人："OppaiSuki"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [Ferry-200/coriander_player] 征求新功能 (Issue #6)




  
1.既然是本地播放器，希望可以提供一个真正的全屏模式，或者说最大化时可以隐藏任务栏？windows的任务栏和目前软件的UI实在是太割裂了，不过这也是PC应用普遍存在的问题。
 2.似乎是不支持触摸板的手势操作，暂停和切歌都没反应,用Powertoys指定程序和快捷键也不行，或许是我的操作问题？
 3.跟随系统深色/浅色模式，这个晚上玉玉的时候打开播放器容易被亮瞎狗眼。
 4.更多歌词页面样式，这个感觉优先度不是很高，我觉得默认的挺好看的
 5.音乐可视化，我在曾经的老手机HTC和PSP上很喜欢开可视化
   
在研究
 2、3. 在进度中
 4、5. 还得考虑一下

**Comment by OxcreeperxO** [comment]
希望可以加一个小功能
本地歌曲扫描的时候好像不会扫描选定文件夹内的子文件夹里的歌
希望可以扫描到

**Comment by Dr-SummerFlower** [comment]
我非常看好这个项目，我希望可以增加一个后台播放的功能，就是任务栏图标那种，在关闭窗口后可以继续播放

**Comment by darkduck9** [comment]
![2](https://github.com/Ferry-200/coriander_player/assets/60059377/440e6070-b0bc-49b5-adb8-d729d87c9d9d)
希望对于标签中没信息的歌曲直接显示文件名，如果能直接用本软件编辑标签就更方便了

**Comment by Ferry-200** [comment]
> ![2](https://github.com/Ferry-200/coriander_player/assets/60059377/440e6070-b0bc-49b5-adb8-d729d87c9d9d)
> 希望对于标签中没信息的歌曲直接显示文件名，如果能直接用本软件编辑标签就更方便了

最新版本的话去设置页文件夹管理那点击刷新按钮就可以直接显示文件名了。至于编辑标签，近期应该不会实现。可以使用音乐标签，很可靠的。

**Comment by darkduck9** [comment]
这个播放器不错，功能齐全，替换了我之前用的安卓本地播放器，可惜只有安卓，大佬可以参考一下https://github.com/namidaco/namida

**Comment by ABCDEFZ-jk** [comment]
歌曲列表右侧希望能有字母排序的提示。截图来自椒盐音乐https://github.com/Moriafly/SaltPlayerSource
![S40603-18030602_com salt music](https://github.com/Ferry-200/coriander_player/assets/142577795/70f2d0e5-f64c-4180-9df9-5489eb20ee84)
