### ISSUE TITLE
优化rust相关结构

### ISSUE THREAD

**Issue by chanmaoganda** [Ferry-200/coriander_player#60]
**Bug 概要**
刚注意到有些地方可能设计的不是很适合rust, 所以准备提个pr?

有些位置传的是&Path, 应该用impl AsRef<Path>
有些unused variable等
我去改一下提个pr

**Comment by Ferry-200** [comment]
好好好，辛苦了。只要不改目录结构的话都可以。

**Comment by chanmaoganda** [comment]
对了, 我做的修改是基于1.80的版本的rust, 你本地编译应该要升级一下,有些api变动了,file.write要处理size了, 替换成write_all这种的
