### ISSUE TITLE
有概率点击关闭键无法关闭

### ISSUE THREAD

**Issue by sjrmdtjws2233** [Ferry-200/coriander_player#62]
**Bug 概要**
在win11系统上有概率点击关闭键无法关闭软件(x64)

**复现步骤*不知道，概率问题

**预期行为**
修复bug

**截图**

https://github.com/user-attachments/assets/3464c557-f67e-40e9-8fb6-9255f7d24016视频

**Comment by JIANHAISITIAN** [comment]
https://github.com/user-attachments/assets/cc1ed8ec-f498-417b-9f8a-5ff01f49198d

**Comment by shing-yu** [comment]
Same problem here.
相同问题
