### ISSUE TITLE
[UI] 或许可以减淡一下上下句歌词的颜色深度

### ISSUE THREAD

**Issue by shing-yu** [Ferry-200/coriander_player#66]
如题

个人感觉上下句歌词的颜色深度有点深了；
一眼看过去还要分辨一下（
感觉可以调的更淡些（
（特别是与后续歌词相比）

![image](https://github.com/user-attachments/assets/74335fd8-e6f7-486a-a46d-afabc159c1f4)

**Comment by Ferry-200** [comment]
有个更激进的想法：直接让上下句和其他的一样浅

**Comment by shing-yu** [comment]
> 有个更激进的想法：直接让上下句和其他的一样浅

也可以（

**Comment by Wenti-D** [comment]
粗测三种颜色 HSV 的 V 值（明度）大概是 13、50、83，但显然 50 和 13 之间对比不够强烈，于是随便选了一些其他的值：
![image](https://github.com/user-attachments/assets/4d936c08-095d-4f52-91d0-3f8e24e08bd7)

**Comment by Silicon7921** [comment]
个人喜欢第二组。

**Comment by Wenti-D** [comment]
> 个人喜欢第二组。第三组90恐怕太浅了，比较难看清。

其实也不是非要一竖条就是一组，比如可以 13-72-85，相比 13-66-85 如何呢？

**Comment by shing-yu** [comment]
我觉得直接一样浅比较好（
因为别忘了有些平台提供的歌词文件是有空行的（

**Comment by Wenti-D** [comment]
> 因为别忘了有些平台提供的歌词文件是有空行的（

但是预处理的时候会去掉所有空白行好像

**Comment by shing-yu** [comment]
> > 因为别忘了有些平台提供的歌词文件是有空行的（
> 
> 但是预处理的时候会去掉所有空白行好像

显示是去掉了空白行，但是颜色渲染没有（

**Comment by Ferry-200** [comment]
空白行没有去掉，只是让它不可见了。这里有我的一些考虑所以改不了。

确实一直忘记了空白行会导致这些效果不统一，所以只着重显示当前行才是最佳的解决方案。而且还能带来一点微不足道的性能优化（

**Comment by Silicon7921** [comment]
如果只加深当前行，希望能略微将其余的深度稍微加深一点，提高易读性。

**Comment by shing-yu** [comment]
> 如果只加深当前行，希望能略微将其余的深度稍微加深一点，提高易读性。

明度77是个不错的值（
大致效果：
![image](https://github.com/user-attachments/assets/11d04213-cc2b-40eb-9015-b7c233d9d786)
