### ISSUE TITLE
（兼容性问题）1.1.0新版本更新后点击设置中的文件夹管理灰屏卡死

### ISSUE THREAD

**Issue by NN19L** [Ferry-200/coriander_player#67]
**Bug 概要**

1.1.0新版本更新后点击设置中的文件夹管理灰屏卡死，只能通过任务栏或任务管理器关闭
**复现步骤**
windows11删除旧版本后安装新版本后直接点击设置中的文件夹管理，exe与zip文件均已尝试，不清楚是软件bug还是个人设备兼容性原因

**预期行为**
找到除将音乐转移到默认文件夹以外的解决方法

**截图**
![图片](https://github.com/user-attachments/assets/561a1188-672f-41c1-8ae3-6c22dd251682)

**Comment by Ferry-200** [comment]
怎么那么多兼容性问题啊😡

**Comment by NN19L** [comment]
啊这，我啥也不造啊，上个版本啥事没有，突然就这样了。
果咩捏。
顺便补一句，把音乐文件拖到默认文件夹似乎也无法识别出来，直接点击音乐文件选择用coriander打开也无解。
不过我觉得我应该是个例，也不用太上心这个问题。

**Comment by Ferry-200** [comment]
啊我没有生气。那我换个 emoji

**Comment by Ntsc-Yrx** [comment]
貌似不是个例啊，会不会缺什么运行库？

**Bug 概要**

1.1.0新版本更新后点击设置中的**前4个标签页**灰屏，无法显示内容。
![image](https://github.com/user-attachments/assets/89b1d02c-0afa-4252-ace5-a3becc1623d3)

**复现步骤**

**windows10 22H2** 直接安装新版本后按正常方法运行，exe与zip文件均已尝试。_

**Comment by Ferry-200** [comment]
@Ntsc-Yrx 转到 #71
