### ISSUE TITLE
建议：增加一个明确的LICENSE文件

### ISSUE THREAD

**Issue by shing-yu** [Ferry-200/coriander_player#69]
如题

建议给仓库明确指定一个许可证，比如[GPL-3.0](https://raw.githubusercontent.com/licenses/license-templates/master/templates/gpl3.txt)或者[MIT](https://raw.githubusercontent.com/licenses/license-templates/master/templates/mit.txt)等；
方便贡献、使用和分支等（

**Comment by Silicon7921** [comment]
推荐GPL-3.0

**Comment by shing-yu** [comment]
确实，这样的软件还是适合GPL，防止有些人剽窃去卖（

**Comment by Ferry-200** [comment]
那就 gpl3.0 吧

**Comment by shing-yu** [comment]
下个发行版的inno setup构建的安装包里也可以加上（
<details>
<summary>添加位置</summary>
<pre><code>[Setup]
LicenseFile=&lt;path to file&gt;\LICENSE
<br>
[Files]
Source: "&lt;path to file&gt;\LICENSE"; DestDir: "{app}"; Flags: ignoreversion
</code></pre>
</details>

以及压缩包（
