### ISSUE TITLE
继承旧版本数据时可能出错

### ISSUE THREAD

**Issue by Ferry-200** [Ferry-200/coriander_player#71]
貌似不是个例啊，会不会缺什么运行库？

**Bug 概要**

1.1.0新版本更新后点击设置中的**前4个标签页**灰屏，无法显示内容。
![image](https://github.com/user-attachments/assets/89b1d02c-0afa-4252-ace5-a3becc1623d3)

**复现步骤**

**windows10 22H2** 直接安装新版本后按正常方法运行，exe与zip文件均已尝试。_

_最初由 Ntsc-Yrx 在 https://github.com/Ferry-200/coriander_player/issues/67#issuecomment-2277779616 发布_

**Comment by Ferry-200** [comment]
如果你有能力的话，可以去 C:\Users\你的用户名\AppData\Roaming\com.example\coriander_player 目录删除 index.json 文件后，再次运行软件。这样可以转到欢迎页。

但是在决定设计旧版本数据和新版本数据不同的时候，我已经测试过从各个旧版本升级到 1.1.0 都不会出现问题。可能出现了特例。

我在这方面没太多经验，忽略了兼容性问题。以后会尽量做好错误处理的。

**Comment by Ntsc-Yrx** [comment]
感谢，问题已经解决。

不过作为用了 4 个月 coriander 的用户来说，觉得把所有文件放在一个文件夹内比较好（因为我主要把 coriander 作为一个便携播放器使用，一方面每次需要重新选择文件夹，另一方面如果已知用的是 zip 版本，也很难想到 `C:\Users\你的用户名\AppData\Roaming\com.example\coriander_player` 目录 还有一个文件。

大爱 coriander。

**Comment by Ferry-200** [comment]
其实新版本发布前我有更改应用数据目录的打算，但因为一些具体的问题没弄。

再者我觉得大部分用户也不会介意我在这里放不到 1mb 的垃圾（
