### ISSUE TITLE
[次要][UI] 建议专辑界面默认按照音轨号排序

### ISSUE THREAD

**Issue by shing-yu** [Ferry-200/coriander_player#74]
相对次要（

MP3和FLAC的标签中均有”音轨号“字段，程序也对其进行了解析
专辑界面也可切换为按照音轨号进行排序

但是我认为专辑界面按音轨号排序应该成为默认：
1. 各大音乐软件大多按照音轨号排序
2. 如果有音轨号，但是未按照音轨号进行排序，会显得比较混乱（
如图：
![image](https://github.com/user-attachments/assets/e1869faa-a1d7-4a2d-8ffe-a9a2383c50da)
3. 可以在没有音轨号时，自动转为按标题或其他的进行排序（

**Comment by Wenti-D** [comment]
~~我超，铁~~
那么，假定在一些极端特殊情形下，一部分有音轨号一部分没有的时候怎么办呢？

**Comment by shing-yu** [comment]
目前的音轨号排序模式会把没有音轨号的音乐的音轨号视为0（
