### ISSUE TITLE
【BUG】专辑封面显示不清晰

### ISSUE THREAD

**Issue by FisherRong** [Ferry-200/coriander_player#75]
**Bug 概要**
专辑封面显示不是很清晰呢

**复现步骤**
看了很多专辑，都是这样

**预期行为**

**截图**
![image](https://github.com/user-attachments/assets/7b28dd84-436a-4a9e-a809-ce600af08313)

**Comment by Ferry-200** [comment]
这是预期行为，故意只加载 400*400 的封面。

**Comment by FisherRong** [comment]
您好，我已收到

**Comment by FisherRong** [comment]
这是这个音频文件。

**Comment by shing-yu** [comment]
不增加点是有什么考虑吗（
因为我感觉对于这么大的图来说，400x400有点捉襟见肘（
甚至实际占的大小都超过400x400像素点了（

**Comment by Ferry-200** [comment]
> 不增加点是有什么考虑吗（
> 因为我感觉对于这么大的图来说，400x400有点捉襟见肘（
> 甚至实际占的大小都超过400x400像素点了（

确实我不应该只加载 400*400，而是 400 * 缩放大小。

另外我有一种见解，应该是错误的。就是图片占多大空间就只解码多大的图片。

**Comment by shing-yu** [comment]
我改800*800测试看看（

**Comment by Ferry-200** [comment]
> 我改800*800测试看看（

我怎么感觉你懂得好多😂

**Comment by shing-yu** [comment]
> > 我改800*800测试看看（
> 
> 我怎么感觉你懂得好多😂

我是Python的开发者，具体可以看主页（
虽然我不会dart和flutter，但是编程语言都有相似的地方嘛（
而且还有GPT（

**Comment by Ferry-200** [comment]
> 我改800*800测试看看（

如果找不到的话，我这里直接给结果

https://github.com/Ferry-200/coriander_player/blob/main/lib%2Fpage%2Fnow_playing_page%2Fpage.dart#L590-L590

https://github.com/Ferry-200/coriander_player/blob/main/lib%2Flibrary%2Faudio_library.dart#L264-L264

这里写得确实有点乱。

**Comment by shing-yu** [comment]
找到了第二个（

**Comment by Ferry-200** [comment]
> 找到了第二个（
> 第一个好像是位置吧（

啊对，只用改第二个

**Comment by shing-yu** [comment]
事实上，我改到1200x1200，都没看到cpu和内存的明显提升（
所以感觉800x800问题不大（
我先pr一下吧（

**Comment by Ferry-200** [comment]
> 事实上，我改到1200x1200，都没看到cpu和内存的明显提升（
> 所以感觉800x800问题不大（
> 我先pr一下吧（

可以，然后后续交流就转到那里。
