### ISSUE TITLE
【建议】自动获取音乐封面的功能

### ISSUE THREAD

**Issue by mintonight** [Ferry-200/coriander_player#76]
希望添加一个自动获取音乐封面的功能

**Comment by Ferry-200** [comment]
比像现在歌词匹配一样，在没有封面的情况下，选取最相似的歌曲获取它的封面来代替？

做是可以做，但是我希望这个功能默认关闭，需要手动启用。

**Comment by mintonight** [comment]
对的，选取最相似的歌曲获取它的封面，默认关闭可以
参考链接：https://post.smzdm.com/p/a60nl7n0/
可以看看这个软件，我目前使用它来获取封面效果不错。

**Comment by Ferry-200** [comment]
感觉有版权问题诶，先标记成未计划
