### ISSUE TITLE
强制改变播放进度可能会使之不准确

### ISSUE THREAD

**Issue by Wenti-D** [Ferry-200/coriander_player#8]
https://github.com/Ferry-200/coriander_player/assets/73067578/6ed19887-481d-4d06-b461-7df2cd0fffdd

在第二遍播放的时候，26s 开头的一句在计时 26s 时实际已经到了一半的位置。

**Comment by Ferry-200** [comment]
https://github.com/Ferry-200/coriander_player/assets/98510207/3172ef46-bad6-4f53-a7e0-a360b8bbb66e

无法复现欸。是偶发情况吗？另外歌很好听

**Comment by Wenti-D** [comment]
哦，我没有表述清楚，再次播放的时候，我直接点了几下进度条来调整播放位置。

**Comment by Wenti-D** [comment]
其实，只要歌曲播放中，随便点进度条（除了开头），就会触发这个问题。最容易观察到的现象就是歌词对不上。

**Comment by Wenti-D** [comment]
https://github.com/Ferry-200/coriander_player/assets/73067578/8e15ba6b-4cad-400b-8f0f-b4924857c976

更加明显的现象。

**Comment by Wenti-D** [comment]
试了一会，当进度条在歌曲前半的时候歌词延后，在后半则超前，有种压缩映射的美。

**Comment by Ferry-200** [comment]
https://github.com/Ferry-200/coriander_player/assets/98510207/9471a38e-5228-4d11-a902-68485a262db2

还是没有复现出来，，，。我也用github上的试了，没有复现

**Comment by Wenti-D** [comment]
等下，出现问题的歌曲好像全是 FLAC？

**Comment by Wenti-D** [comment]
感觉长曲（6 分钟及以上）基本上都有这个问题

**Comment by Ferry-200** [comment]
https://github.com/Ferry-200/coriander_player/assets/98510207/de77786c-28f8-4fbb-a4f8-065bdfbf01c1

还是没有复现出来，，，。我这里歌词和间奏动画都是直接跟进度绑定的，没有加独立的计时器。出问题也只能是Bass音频库的问题。明天我再翻翻它的论坛看有没有人反馈进度不准确的问题吧。

**Comment by Ferry-200** [comment]
大概找出问题所在了
[BASS_ChannelSetPosition problem](https://www.un4seen.com/forum/?topic=20197.0)

其实就是：我发现不需要加载bassflac插件也可以播放flac的音乐，所以就偷懒了。不加载这个插件，在播放flac时会使用Windows Media Foundation，这可能是seek不准确的原因。

方便的话可以加qq：2110197157来进行测试吗？

**Comment by Wenti-D** [comment]
啊，倒没有不方便。不过既然现在有网盘了，就先在网盘下载，如果后续还有需求就通过 QQ 测试吧。

**Comment by Wenti-D** [comment]
现在好了。
