### ISSUE TITLE
【建议】1.能否支持中文排序 2.能否添加一个默认的【我喜欢】这种的歌单，然后弄个爱心什么的方便添加到里面

### ISSUE THREAD

**Issue by wuyou1024** [Ferry-200/coriander_player#85]
1.现在标题排序好像是纯英文，中文歌的排序完全是乱的，找不到任何规律，中文排序可以参考手机上的otomusic
2.如题，同样可参考otomusic
![图片](https://github.com/user-attachments/assets/bf7cb20c-13bb-47f9-b1d5-629e42fc5c35)

**Comment by Ferry-200** [comment]
中文的排序是使用康熙字典上的部首排序，这是 unicode 里中文的字典序，几乎所有编程语言的默认排序都是使用这种顺序。
确实应该改成拼音排序。后面再改吧。

第二点的话，新建一个歌单也不麻烦吧。而且现在右键可以进入多选了，也没有那么麻烦了。后面再出个定位到当前正在播放的歌曲的功能就更方便了。
