### ISSUE TITLE
[改进] 非正方形封面显示

### ISSUE THREAD

**Issue by mintonight** [Ferry-200/coriander_player#87]
### 附带PR？

否

### 功能描述

对于封面不是正方形的音乐在播放界面的显示形式
## 效果对比
`coriander_player`的显示逻辑是将图片尺寸变形为正方形观感有些奇怪
![image](https://github.com/user-attachments/assets/227eada7-0ba8-4c3f-a70f-de80a22e3db0)
`网易云+betterncm`的显示逻辑是截取中间的部分作为封面效果不错
![image](https://github.com/user-attachments/assets/6186c351-2ca5-4e31-aaf8-7e886ddec780)
`potplayer`直接显示长方形感觉也挺好的
![image](https://github.com/user-attachments/assets/bd84ae5a-0a0b-4379-a7ad-8cdbbe08ed69)

### 被改进功能的分类（选填）

UI

**Comment by shing-yu** [comment]
这个似乎和 #75 #80 相关的代码有点关系
似乎是强制转换为1x1比例的分辨率了（
或许可以加个中间区域裁剪？

**Comment by mintonight** [comment]
裁切可以的，类似网易云现在的方案

**Comment by Ferry-200** [comment]
> 这个似乎和 #75 #80 相关的代码有点关系
> 似乎是强制转换为1x1比例的分辨率了（
> 或许可以加个中间区域裁剪？

这个问题一直有人提，但我从来没怀疑过是那里导致的🥲
等明天我仔细看看。

**Comment by Ferry-200** [comment]
https://api.flutter.dev/flutter/painting/ResizeImage/ResizeImage.html

https://api.flutter.dev/flutter/painting/ResizeImagePolicy.html

默认参数（ResizeImagePolicy.exact）是忽略原来的比例；

然后 ResizeImagePolicy.fit 就是保留原来的比例。

这下终于能解决了😋

**Comment by Ferry-200** [comment]
done
![image](https://github.com/user-attachments/assets/d043a165-e552-465b-a098-b508ac468055)
