### ISSUE TITLE
[BUG] 扫描进的歌曲部分不能正确匹配歌名、时长以及其他信息

### ISSUE THREAD

**Issue by Hakutyou0411** [Ferry-200/coriander_player#88]
### 附带PR？

否

### 版本

1.1.0

### 问题描述

![屏幕截图 2024-08-14 002943](https://github.com/user-attachments/assets/65b9e434-1bcf-4656-8da3-24be7c041ea2)
![屏幕截图 2024-08-14 003053](https://github.com/user-attachments/assets/9af95298-22ff-42ff-bf55-c575be596b60)
扫描发现一部分导入正常而另一部分导入错误的信息

### 重现步骤

扫描文件夹

### 预期行为

识别正确的歌曲名、歌曲时长以及其他相关信息

**Comment by Ferry-200** [comment]
几乎没有有效信息🥲

**Comment by Ferry-200** [comment]
你好歹把第二张截图截完整给我啊🥲

**Comment by shing-yu** [comment]
你可能至少需要提供一个文件

**Comment by Ferry-200** [comment]
转到 #90
