### ISSUE TITLE
[BUG] 某些情况下，随机播放会失效

### ISSUE THREAD

**Issue by xiaoyu606** [Ferry-200/coriander_player#91]
### 附带PR？

是

### 版本

1.1.0

### 问题描述

我听歌有个习惯，就是开随机播放模式，我个人并不喜欢列表循环，但我在使用这个软件听歌时发现，在某些情况下，随机播放会失效，哪怕随机**播放按钮已点亮**，下一曲依然会**按照列表顺序播放**，详细复现步骤我将在“重现步骤”一栏进行描述

### 重现步骤

1.打开软件
2.点击“随机播放”按钮，开始播放音乐，此时播放下一曲，正常随机播放
3.在主界面的列表里随便播放一首曲目
4.现在再播放下一首，就会发现软件不再随机播放，而是列表播放，但是随机播放的按钮依然是点亮的
5.想要重新回到随机播放，就要在播放页面里把随机播放关掉再重新打开

### 预期行为

我预期的行为是：在主界面播放音乐后，随机播放依然可用，下一曲依然是随机播放

### 其他信息

补充信息：我当前列表排序为按修改时间排序，降序

**Comment by Ferry-200** [comment]
是我忘记了🥲，不过这个好修

**Comment by xiaoyu606** [comment]
@Ferry-200 我手滑点错了，抱歉抱歉😅
