### ISSUE TITLE
[改进] “随机播放”似乎并不随机

### ISSUE THREAD

**Issue by windowBR** [Ferry-200/coriander_player#92]
### 附带PR？

否

### 功能描述

随机播放打开后似乎并不是真的在随机播放，比如我首次播放 A，随机到下一首是 B，再下一首是 C，以此类推；
那么即使当我关闭软件再次打开，播放 A，下一首、下下首也一定是 B、C；
重启软件从 B 开始播放，那么后续一定会是 C、D、E。
希望能优化一下随机算法避免该情况，至少也希望做到每次重启软件就将随机队列打乱，目前这种逻辑很大的问题在于一般打开软件后都会点击靠前的歌曲，但由于播放队列已固定，那么必然会有相当大数量的歌曲无法被播放。

### 被改进功能的分类（选填）

随机播放逻辑

**Comment by Ferry-200** [comment]
啊是这样的吗，我从来没注意过🤣
