### ISSUE TITLE
[BUG] 无法添加「自定义艺术家分隔符」

### ISSUE THREAD

**Issue by Wenti-D** [Ferry-200/coriander_player#93]
### 附带PR？

否

### 版本

1.1.0，但是来自 #86 发给我的测试版

### 问题描述

设置页中的「自定义艺术家分隔符」可以删除项，但无法添加项，添加任意项均会变成空白。

### 重现步骤

1. 随便添加一个自定义艺术家分隔符（我试过 「；」「;」「六」「6」「/」）；
2. 点【确定】；
3. 再点击【管理艺术家分隔符】查看，你会看到刚刚添加的变成了空白。

### 预期行为

理应能记下刚刚输入进去的分隔符。

**Comment by Ferry-200** [comment]
你有在输入完回车符后按过回车吗🧐

我这里忘记做 UI 引导了

**Comment by Wenti-D** [comment]
我倒觉得直接点确定的时候就不需要再前置回车了，这样更自然。

进一步而言，在没有按回车的时候，如果操作底下的按钮，应该就相当于按了回车之后再操作。

**Comment by Ferry-200** [comment]
确实是，待会会加
