### ISSUE TITLE
[改进] 界面相关的问题

### ISSUE THREAD

**Issue by will5933** [Ferry-200/coriander_player#94]
### 附带PR？

否

## 1
![PixPin_2024-08-16_20-05-15](https://github.com/user-attachments/assets/b588e174-0096-4fb9-b433-f4499dd17583)
![PixPin_2024-08-16_20-05-53](https://github.com/user-attachments/assets/7f34ce9b-2483-4295-8b65-728faba18cae)
首页的歌曲列表界面里的音乐标题和下面的艺术家/专辑字体能不能稍微优化下 😭 就像播放界面的那样就好（↓）
还有就是大部分歌曲都是一小时以内，大概可以把时长中的小时省略了？
![图片](https://github.com/user-attachments/assets/3f451f0a-3fdd-473d-8546-5986fbb6ae54)

## 2
![PixPin_2024-08-16_20-09-38](https://github.com/user-attachments/assets/9a4c8f55-12dd-401f-9bd7-cefb9e40bb9c)
PC 上这个返回按钮好像没什么用

## 3
![PixPin_2024-08-16_20-11-57](https://github.com/user-attachments/assets/40c8d3c8-4ca4-4ff8-b698-5b3b29ef381d)
![PixPin_2024-08-16_20-12-17](https://github.com/user-attachments/assets/58a76fc0-aea0-4c1b-89a0-213069523827)
专辑页面显示好像有点问题？

## 4
自定义字体或者软件自带个多字重的字体，HarmonyOS Sans 、Noto Sans 或者 MiSans VF，Windows自带这不是很好看，多语言显示时字重不一样。
![图片](https://github.com/user-attachments/assets/ab046fa8-82e9-4fcc-8989-4201396290ef)

## 5
最小化到系统托盘（tray）处理，总是习惯性点 x 号，软件就直接退出了。

## 6
![图片](https://github.com/user-attachments/assets/c7ca9c3d-e389-4647-b4b8-c242b02f768a)
上面这个条条是什么？我以为是搜索框，点了没什么用。

> 就这些吧，可能提的比较主观一些，希望能帮上忙 🤪

**Comment by Ferry-200** [comment]
1. 可以
2. 有用的，我经常用
3. 确实，我看看怎么改
4. 那个不是 bug 是有意这么设计的。上面是原文下面是翻译，然后把上面的加粗以强调原文
5. 不喜欢
6. 那个是显示歌词的。
