### ISSUE TITLE
[新功能] 系统托盘支持/禁止多实例启动

### ISSUE THREAD

**Issue by Windla** [Ferry-200/coriander_player#95]
### 附带PR？

否

#### 系统托盘支持
希望设置中能提供`最小化到系统托盘`和`关闭到系统托盘`等相关系统托盘功能

这是Dopamine3.0的相关设置参考
![image](https://github.com/user-attachments/assets/501d3941-15e3-49cb-9229-d6e1cb6358db)
![image](https://github.com/user-attachments/assets/41d2ed35-8c22-4adf-b0f4-3746e8b97cc4)

#### 禁止多实例启动
如题，二次启动切换到已启动的窗口

**Comment by Ferry-200** [comment]
系统托盘功能这么重要吗？🧐那么多人想要

**Comment by shing-yu** [comment]
可以加个开关（

**Comment by Windla** [comment]
> 系统托盘功能这么重要吗？🧐那么多人想要

按照我个人的操作使用习惯来说，将系统托盘功能作为后台留存的可选项和关闭行为是挺不错的。
换一个说法就是，我希望可以仅关闭界面而不是关闭程序，即使仅关闭界面仍可以使用多煤体键进行后台切换。
仅关闭界面并不是不喜欢您的UI设计之类的，对于系统托盘的菜单实现`显示Coriander Player`和`退出`就足以。

另外抱歉对您造成了困恼，我此前在浏览issue的过程中并未注意到您不喜欢系统托盘，若您无此计划请`Close as not planned`，打扰了。

**Comment by Ferry-200** [comment]
确实最近无计划，等以后再说吧
