### ISSUE TITLE
[改进] 希望能添加卡片边框

### ISSUE THREAD

**Issue by Yur1et** [Ferry-200/coriander_player#97]
### 附带PR？

否

### 功能描述

![1](https://github.com/user-attachments/assets/e1377a20-1047-4234-8ee7-5dd877237354)
列表选项之间没有间距，看起来过于紧凑。适当增加一点间距视觉效果更优

### 被改进功能的分类（选填）

UI

**Comment by Ferry-200** [comment]
我觉得还好🧐

另外，你的系统语言是英语吗？有没有发现播放器的字体很奇怪
